import 'bootstrap-icons/font/bootstrap-icons.css'; //import bootsrap icons
import 'bootstrap/dist/css/bootstrap.css'; // import bootstrap css
import '@/components/preloader.css'; // import preloader css



import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./variables.css";
import "./globals.css";
import Header from '@/components/Header';


const ebGaramond = EB_Garamond({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const ebGaramond1 = EB_Garamond({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital New App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.variable} ${ebGaramond1.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
